services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # simple dev password
      POSTGRES_DB: langgraph
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  # plan-execute:
  #   build: .
  #   restart: unless-stopped
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PORT}:${PORT}"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
